[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["python -m pip install -r ten-no-koe-backend/requirements.txt"]

[start]
cmd = "cd ten-no-koe-backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"