[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r ten-no-koe-backend/requirements.txt"]

[start]
cmd = "cd ten-no-koe-backend && uvicorn main:app --host 0.0.0.0 --port $PORT"